[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

[[redirects]]
  from = "/post"
  to = "/404"
  status = 404
  force = true
[[redirects]]
  from = "/post/index.html"
  to = "/404"
  status = 404
  force = true
