backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Jumbotron", name: jumbotron, widget: object, fields: [
              {label: "Pre-Title", name: "title_pre", widget: string},
              {label: "Post-Title", name: "title_post", widget: string},
              {label: "Item 1", name: "item1", widget: string},
              {label: "Item 2", name: "item2", widget: string},
              {label: "Item 3", name: "item3", widget: string},
            ]}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading Image", name: "heading-image", widget: "image"},
              {label: "Heading", name: "heading", widget: string},
              {label: "Subheading", name: "subheading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Key Points", name: twoup, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Description", name: "description", widget: "text"},
              {label: "Blurbs", name: blurbs, widget: list, fields: [
                {label: "Image", name: "image", widget: "image"},
                {label: "Text", name: "text", widget: "text"}]}
              ]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
